# Please make sure to update the license_key information with the license key for your New Relic
# account.
#
#
newrelic:
  #
  # Update with your New Relic account license key:
  #
  license_key: 'YOUR_LICENSE_KEY_HERE'
  #
  # Set to '1' for verbose output, remove for normal output.
  # All output goes to stdout/stderr.
  #
  # verbose: 1
#
# Agent Configuration:
#
agents:
  passenger:
    # Adjust the path to your passenger commands as appropriate
    passenger_status: '/usr/local/bin/passenger-status'
    passenger_memory_stats: '/usr/local/bin/passenger-memory-stats'
    passenger_version: 5 #May be 3, 5 or 5
